### ISSUE TITLE
Please consider allowing forks for pull requests only.

### ISSUE THREAD

**Issue by ShikiSuen** [CanglongCl/Genshin-Pizza-Helper#5]
I have previously communicated to one of your devs on Bilibili before, and I was told that there are limited development resources to add display support for accessory levels (圣遗物等级).

Today, I was about to fork this repository to see whether I can develop this feature (and make pull requests if I made it). However, this ends up with your statements of "NO LICENSE" for now.

Therefore, may I confirm whether you devs can make exceptions to allow others contribute to this repository? If that comes true, my feature requests will be focused on improving the app experience on macOS, considering that this is (currently) the only Genshin utility app available on macOS.

**Comment by Bill-Haku** [comment]
Hello, thanks for you kindness! We are happy to see anyone who wants to contribute to our project, but we temporarily do not want anyone to redistribute this app so we released this repo under no license. if you are willing to contribute, we can invite you to the private develop repo so that you can access the latest code. is the email on you profile `shikisuen@pm.me` your GitHub account email?

**Comment by ShikiSuen** [comment]
@Bill-Haku Thanks for your response. I just got in touch with Lava. See you later in Feishu.
